### ISSUE TITLE
Thông Báo về việc Báo cáo môn Quản Lý Công Nghệ Thông Tin

### ISSUE THREAD

**Issue by rinodung** [rinodung/quan-ly-cong-nghe-thong-tin#1]
**Đề Tài**: **KỸ NĂNG CẦN THIẾT CỦA MỘT CIO TRONG MỘT DOANH NGHIỆP OUTSOURCING.**

**Thành viên:**
1. Đồng Tiến Dũng
2. Nguyễn Dung Hạnh
3. Trần Thị Thu Thúy

**Thời gian báo cáo:** 27-02-2106

**Hình thức báo cáo**: chuẩn bị slide thuyết trình

**Công việc cần làm**
Nội dung bài báo cáo sẽ chia ra làm 3 phần(em sẽ gán issue sau):
1. Outsourcing là gì?(Hạnh) #2 
2. CIO là gì?(Thúy) #3 
3. Những kỹ năng cần thiết của một CIO trong doanh nghiệp OUTSOURCING(Dũng)

Mọi người chuẩn bị phần của mình sau đó sẽ làm slide chung qua: https://docs.google.com/presentation/d/1mlKxEpSW8Ghuyp7LOJAwwDu91XD9BZRBNfcuBsxbFmQ/edit?usp=sharing

trước thứ 5(25-02) phải có slide để hiệu chỉnh lần cuối

**Comment by rinodung** [comment]
Vui lòng comment bên dưới mỗi issue  để biết là đã nhận được issue này nhé các chị?

**Comment by Dunghanh** [comment]
ok
